Update pages.yaml

diff --git a/.github/workflows/pages.yaml b/.github/workflows/pages.yaml
--- a/.github/workflows/pages.yaml
+++ b/.github/workflows/pages.yaml
@@ -1,39 +1,31 @@
-name: Update Detectable
+name: Update Detectable Games List
 
 on:
   schedule:
-    - cron: '0 0 * * *' # every day at midnight
-  workflow_dispatch:
+    - cron: '0 0 * * *' # Daily at midnight UTC
+  workflow_dispatch: # Manual trigger
 
 jobs:
-  pages_deploy:
-    # Required permissions for GitHub Pages deployment
+  update_and_deploy:
     permissions:
       contents: read
       pages: write
       id-token: write
-    # Required for GitHub Pages deployment
     environment:
       name: github-pages
-      url: ${{steps.deployment.outputs.page_url}}
+      url: ${{ steps.deployment.outputs.page_url }}
     runs-on: ubuntu-latest
     steps:
-      - name: Fetch Game list
+      - name: Fetch Discord Detectable Games
         shell: bash
-        env:
-          DETECTABLE_ENDPOINT: ${{ secrets.DETECTABLE_ENDPOINT }}
-          DETECTABLE_VERSIONED_ENDPOINT: ${{ secrets.DETECTABLE_VERSIONED_ENDPOINT }}
-          DETECTABLE_VERSION: ${{ vars.DETECTABLE_VERSION }}
         run: |
-          curl -fsSL -o detectable.json $DETECTABLE_ENDPOINT || echo '{}' > detectable.json
-          curl -fsSL -o detectable_${DETECTABLE_VERSION}.json $DETECTABLE_VERSIONED_ENDPOINT || echo '{}' > detectable_${DETECTABLE_VERSION}.json
-
-          [ ! -s detectable.json ] && echo "detectable.json is empty"
-          [ ! -s detectable_${DETECTABLE_VERSION}.json ] && echo "versioned json is empty"
-
           mkdir -p dist
-          mv detectable.json dist/
-          mv detectable_${DETECTABLE_VERSION}.json dist/
+          curl -fsSL -o dist/gamelist.json https://discord.com/api/v9/applications/detectable || echo '[]' > dist/gamelist.json
+          
+          if [ ! -s dist/gamelist.json ]; then
+            echo "Failed to fetch game list"
+            exit 1
+          fi
 
       - name: Upload GitHub Pages artifact
         uses: actions/upload-pages-artifact@v3
